# This file was generated by GoReleaser. DO NOT EDIT.
cask "nummion" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fc234bd3752567607b7874f57d35a396156857ddf5c43c380b7747913fa1e890"
      url "https://github.com/JangoCG/nummion/releases/download/v#{version}/nummion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "585cd3dc451aa3e2d61a83947dc04dd4acd79ad1831e1671267de015e44db78f"
      url "https://github.com/JangoCG/nummion/releases/download/v#{version}/nummion_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c4d44b113b54df46542f934db3e262e40f60b53cd7681dad79b980ffd3f4f38f"
      url "https://github.com/JangoCG/nummion/releases/download/v#{version}/nummion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f364cd1b70df6c876fd1ff200a39e4d0055fb206cfecf452ac25aa434ee76673"
      url "https://github.com/JangoCG/nummion/releases/download/v#{version}/nummion_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nummion"
  desc "Unofficial Lexware Office CLI — run it with num"
  homepage "https://github.com/JangoCG/nummion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "num"
  bash_completion "completions/num.bash"
  fish_completion "completions/num.fish"
  zsh_completion "completions/_num"

  # No zap stanza required
end
